#!/usr/bin/env node

const { execFileSync } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');

const rootDir = path.resolve(__dirname);
const nodeGyp = path.join(rootDir, 'node_modules', 'node-gyp', 'bin', 'node-gyp.js');
const nativeDir = path.join(rootDir, 'native');

if (!fs.existsSync(nodeGyp)) {
  throw new Error(
    `node-gyp binary not found at ${nodeGyp}. Run npm install before building native addons.`,
  );
}

execFileSync(process.execPath, [nodeGyp, 'configure'], {
  cwd: nativeDir,
  stdio: 'inherit',
});
execFileSync(process.execPath, [nodeGyp, 'build'], {
  cwd: nativeDir,
  stdio: 'inherit',
});

execFileSync(process.execPath, [path.join(rootDir, 'scripts', 'copy-native-addon.js')], {
  cwd: rootDir,
  stdio: 'inherit',
});
