#!/usr/bin/env node

const { execFileSync } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');

const rootPackageDir = path.resolve(__dirname);
const nodeGyp = path.join(rootPackageDir, 'node_modules', 'node-gyp', 'bin', 'node-gyp.js');

if (!fs.existsSync(nodeGyp)) {
  throw new Error(
    `node-gyp binary not found at ${nodeGyp}. Run npm install before building native addons.`,
  );
}

execFileSync(process.execPath, [nodeGyp, 'configure'], {
  cwd: rootPackageDir,
  stdio: 'inherit',
});
execFileSync(process.execPath, [nodeGyp, 'build'], {
  cwd: rootPackageDir,
  stdio: 'inherit',
});
